name: Semantic Versioning Workflow

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  determine_and_tag_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Necessary to fetch all tags

      - name: Determine Semantic Version
        id: semver
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"

      - name: Append -dev to version
        run: echo "VERSION_WITH_SUFFIX=v${{ steps.semver.outputs.version }}-dev" >> $GITHUB_ENV

      - name: Create and Push Tag
        run: |
          TAG=$VERSION_WITH_SUFFIX
          echo "Creating tag: $TAG"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
