name: Semantic Versioning Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  determine_semantic_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'  # Fetch all history for all tags and branches

      - name: List all tags
        run: git tag

      - name: Determine Semantic Version
        id: semver
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-dev"
          debug: true

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists"
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Tag does not exist"
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi
        env:
          TAG: "v${{ steps.semver.outputs.version }}"

      - name: Create and Push Tag
        if: env.TAG_EXISTS == 'false'
        run: |
          TAG="v${{ steps.semver.outputs.version }}"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
